### ISSUE TITLE
Ghoul barks

### ISSUE THREAD

**Issue by matiasautio** [M4R774/ldjam53#46]
Like
- paketti, paketti...
- siellä se on!
- pysähdy!

and a death sounds

Perttu could voice act

**Comment by M4R774** [comment]
Perttua painostettu asian suhteen

**Comment by Persikkapepe** [comment]
Recorded few voice lines with my own high-pitched voice and then the same lines with a ghoul growl. Recordings submitted to Mr. Martikainen via Telegram.

**Comment by M4R774** [comment]
Tämä otettu työn alle
